name: 🕹 Non-pipeline testing

on:
  workflow_dispatch:
    inputs:
      autonomyLevel:
        description: "Autonomy level (assistant/wopee):"
        required: true
        default: "wopee"
        type: choice
        options:
          - wopee
          - assistant
      botActions:
        description: "Actions bot should do (if wopee):"
        required: false
        default: 5

jobs:
  wopee:
    if: github.event.inputs.autonomyLevel == 'wopee'
    name: 🐒 Wopee bot testing
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      test_config: wopee/dronjo.cloud.yaml
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Get last package version
        run: gh release download --repo autonomous-testing/bot-mvp --archive zip --dir dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_30D_EXPIRATION }} # Set new PAT when expires https://github.com/settings/tokens

      - name: Install wopee
        run: |
          pip install dist/*.zip
          playwright install

      - name: Update config
        run: |
          echo "TODO: This will work only for config with specifit 10 action set. Improve the sed command to more general replacement"
          sed -i 's/number_of_actions: 10/number_of_actions: ${{ github.event.inputs.botActions }}/g' $test_config

      - name: Run wopee tests
        run: |
          sed -i 's/neo4j_password: get.from.sercets/neo4j_password: ${{ secrets.NEO4J_PSWD }}/g' $test_config
          bot_mvp $test_config
        env:
          VRT_API_KEY: ${{ secrets.VRT_API_KEY }}

      - name: Collect logs
        run: |
          mkdir logs
          mv bot.errors.log logs
          mv bot.log logs

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: wopee-logs
          path: logs/
          retention-days: 30

  regression-w-assitant:
    if: github.event.inputs.autonomyLevel == 'assistant'
    name: 🏋️ Wopee assistant testing
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run assistant
        env:
          VRT_API_KEY: ${{ secrets.VRT_API_KEY }}

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
