name: Wopee Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# on:
#   workflow_run:
#     workflows: ["pages build and deployment"]
#     types:
#       - completed

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: "3.x"
          architecture: "x64"

      # - name: Get last package version
      # TODO:
      # run: curl -fsSL https://github.com/autonomous-testing/bot-mvp/releases/download/0.1.2/bot_mvp-0.1.2-py3-none-any.whl -O
      - name: Install wopee
        run: |
          pip install bot_mvp-0.1.2-py3-none-any.whl
          playwright install

      - name: Run wopee tests
        run: bot_mvp wopee/dronjo.cloud.yaml

      - name: Collect logs
        run: |
          mkdir logs
          mv bot.errors.log logs
          mv bot.log logs

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: wopee/
          retention-days: 30
